// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byzhlupdfodwwzvvsnuc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5emhsdXBkZm9kd3d6dnZzbnVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NTMwNTEsImV4cCI6MjA2MDIyOTA1MX0._5CneCjYU8FR2XgQCHtMyV_yV9eH1YentvVV3utaffM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);